### ISSUE TITLE
Remove Publication List page

### ISSUE THREAD

**Issue by anonoz** [kuanhoong/FCI_FYP_Template#3]
I am not sure but, it seems like this Publication List page is added by Overleaf. But then I also saw this part in the .cls file:

```tex
\RequirePackage{multibib}
\newcites{own}{\texorpdfstring{PUBLICATION LIST}{Publication List}}
%\newcites{own}{Publication List}
\bibliographystyleown{apacite}
%\addtoiargdef{\bibliographyown}{}{\setcounter{lbibcount}{0}}
%{\renewcommand*\bibname{\texorpdfstring{PUBLICATION LIST}{Publication List}}}
```

I wonder what can we do to remove that page? Or are there reasons to keep it that we didn't know?

**Comment by kuanhoong** [comment]
Yeah, I think you can remove it. If a student published conference paper then it will be shown there. (Legacy from postgraduate thesis template)
